[tool.commitizen]
name = "cz_conventional_commits"
version = "1.1.0"
version_files = [
    "frontend/package.json:version",
    "VERSION",
    "backend/VERSION"
]
tag_format = "v$version"
update_changelog_on_bump = true