repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.12.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: version-bump
        name: Auto version bump
        entry: ./scripts/version-bump.sh
        language: script
        stages: [pre-push]
