name: ai-recommendation-service
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Python version
  - python=3.11

  # FastAPI and server
  - fastapi=0.104.*
  - uvicorn=0.24.*
  - pydantic=2.5.*

  # Database and storage
  - psycopg2=2.9.*
  - sqlalchemy=2.0.*
  - asyncpg=0.29.*

  # AI/ML libraries (conda-forge has optimized versions)
  - scikit-learn=1.3.*
  - numpy=1.24.*
  - pandas=2.1.*
  - spacy=3.7.*
  - transformers=4.36.*

  # NLP and text processing
  - nltk=3.8.*
  - beautifulsoup4=4.12.*

  # HTTP and requests
  - httpx=0.25.*
  - requests=2.31.*

  # Utilities
  - python-multipart=0.0.*

  # Development tools
  - pytest=7.4.*
  - pytest-asyncio=0.21.*
  - black=23.11.*
  - isort=5.12.*
  - flake8=6.1.*
  - mypy=1.7.*
  
  # Database migrations
  - alembic=1.13.*

  # Excel support
  - openpyxl=3.1.*

  # Pip dependencies (for packages not available in conda)
  - pip
  - pip:
      - pydantic-settings==2.1.0
      - databases[postgresql]==0.8.0
      - aiosqlite==0.19.0
      - openai==1.3.0
      - huggingface-hub==0.20.3
      - feedparser==6.0.10
      - python-jose[cryptography]==3.3.0
      - passlib[bcrypt]==1.7.4
      - pytest-mock==3.12.0
      - pytest-cov==4.1.0
      - pytest-xdist==3.5.0
      - responses==0.24.1
      - fakeredis==2.20.1
      - faker==20.1.0
      - factory-boy==3.3.0
      - pytest-postgresql==5.0.0
      - pre-commit==3.6.0
      - commitizen==3.12.0
      - watchdog==3.0.0
      - ipython==8.17.2
      - jupyter==1.0.0
