/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nopqosykzqtznwodsleb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vcHFvc3lrenF0em53b2RzbGViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MzY1MjcsImV4cCI6MjA2OTQxMjUyN30.2igr4Pv_m6-_Cgj1-dJiEbwWWzbE2_N9lX1N2IVBI3s"